### PR TITLE
Add check for idiomatic swap

### PR DESCRIPTION
**Pull request by pheanex**

### CODE REVIEW

**Comment by pheanex** [comment]
Would squash commits when finished.

**Comment by brycepg** [comment]
Looks good so far. If you're pushing for this checker to be an extension make sure it's recorded in the extensions docs, otherwise no one will use it

**Comment by pheanex** [comment]
Thank you for the review. I was not sure if adding this as an extension is the best way to go. I'd personally prefer to have it on as a default somehow. What do you think?
By the way: Do you know if there is any formal process for deciding on a message code?

**Comment by brycepg** [comment]
Yeah I think putting it in as a checker is fine. It seems like you've taken care of all/most of the potential false-positives.

I don't think there is anything formal. Decide which category you think it goes in, and pick a n+1 number or skip by 100 if you'd like

**Comment by pheanex** [comment]
Ok, i guess I'll move the checker to the refactoring.py module, since I think it best fits there.
I'll then also convert the tests from unit- to functional-tests as this is apparently the way to go with non-extension-checkers.
If you or anyone else has any additional comments or feedback or ideas in how to break the checker and create false positives or the like, please don't hesitate to add them here :smile:

**Pull request closed without merging**
